export const EMPTY_PROJECT = {
	title: '',
	description: '',
	mdBody: '',
	author: '',
	githubRepo: '',
	demo: '',
	phoneImg: null,
	desktopImg: null,
	projectType: 'frontend',
	tecnologies: [],
};

export const PROYECT_TYPES = [
	{ value: 'frontend', label: 'Frontend' },
	{ value: 'backend', label: 'Backend' },
	{ value: 'other', label: 'Other' },
];

export const TECNOLOGIES = [
	'react',
	'react-router',
	'react-query',
	'react-hook-form',
	'javascript',
	'typescript',
	'node',
	'express',
	'html',
	'css',
	'bootstrap',
	'tailwind',
	'angular',
	'passport',
	'material-ui',
	'chakra-ui',
	'java',
	'c#',
	'postgresql',
	'mongodb',
	'git',
	'github',
	'vite',
	'npm',
];
